<?php
/**
 * SMS Panel - Installation Script v1.2
 * 
 * This script will:
 * 1. Check system requirements
 * 2. Create database and tables
 * 3. Create admin user
 * 4. Set up initial gateway (optional)
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$step = $_GET['step'] ?? 'check';
$error = '';
$success = '';

// Handle installation
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step === 'database') {
        $dbHost = $_POST['db_host'] ?? 'localhost';
        $dbUser = $_POST['db_user'] ?? 'root';
        $dbPass = $_POST['db_pass'] ?? '';
        $dbName = $_POST['db_name'] ?? 'sms_panel';
        
        try {
            // Connect without database
            $pdo = new PDO("mysql:host={$dbHost}", $dbUser, $dbPass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create database if not exists
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `{$dbName}`");
            
            // Read and execute schema
            $schema = file_get_contents(__DIR__ . '/schema.sql');
            
            // Split by semicolon and execute each statement
            $statements = array_filter(array_map('trim', explode(';', $schema)));
            foreach ($statements as $stmt) {
                if (!empty($stmt) && !preg_match('/^(--|#|\/\*)/', trim($stmt))) {
                    try {
                        $pdo->exec($stmt);
                    } catch (PDOException $e) {
                        // Ignore some errors like "table already exists"
                        if (strpos($e->getMessage(), 'already exists') === false &&
                            strpos($e->getMessage(), 'Duplicate') === false) {
                            // Log but continue
                        }
                    }
                }
            }
            
            // Update config file
            $configContent = "<?php
/**
 * SMS Panel Configuration
 * Generated by installer on " . date('Y-m-d H:i:s') . "
 */

// Database Configuration
define('DB_HOST', '{$dbHost}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');
define('DB_NAME', '{$dbName}');

// Anti-Spam Configuration
define('SPAM_INTERVAL', 60);

// Application Settings
define('APP_NAME', 'SMS Panel');
define('APP_VERSION', '1.2');
define('TIMEZONE', 'Europe/Moscow');

date_default_timezone_set(TIMEZONE);

// Error reporting (set to 0 in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);
";
            
            file_put_contents(__DIR__ . '/includes/config.php', $configContent);
            
            // Create required directories
            @mkdir(__DIR__ . '/logs', 0755, true);
            @mkdir(__DIR__ . '/exports', 0755, true);
            
            header('Location: install.php?step=admin');
            exit;
            
        } catch (PDOException $e) {
            $error = 'Database error: ' . $e->getMessage();
        }
    }
    
    if ($step === 'admin') {
        $adminUser = trim($_POST['admin_user'] ?? 'admin');
        $adminPass = $_POST['admin_pass'] ?? '';
        $adminName = trim($_POST['admin_name'] ?? 'Administrator');
        $adminEmail = trim($_POST['admin_email'] ?? '');
        
        if (empty($adminUser) || empty($adminPass)) {
            $error = 'Username and password are required';
        } elseif (strlen($adminPass) < 6) {
            $error = 'Password must be at least 6 characters';
        } else {
            try {
                require_once __DIR__ . '/includes/config.php';
                require_once __DIR__ . '/includes/database.php';
                
                $db = Database::getInstance();
                
                // Check if admin already exists
                $existing = $db->fetchOne("SELECT id FROM users WHERE username = ?", [$adminUser]);
                if ($existing) {
                    // Update existing admin
                    $db->query(
                        "UPDATE users SET password = ?, name = ?, email = ? WHERE username = ?",
                        [password_hash($adminPass, PASSWORD_DEFAULT), $adminName, $adminEmail ?: null, $adminUser]
                    );
                } else {
                    // Create new admin
                    $db->query(
                        "INSERT INTO users (username, password, name, email, role, is_active) VALUES (?, ?, ?, ?, 'admin', 1)",
                        [$adminUser, password_hash($adminPass, PASSWORD_DEFAULT), $adminName, $adminEmail ?: null]
                    );
                }
                
                header('Location: install.php?step=gateway');
                exit;
                
            } catch (Exception $e) {
                $error = 'Error: ' . $e->getMessage();
            }
        }
    }
    
    if ($step === 'gateway') {
        $gwName = $_POST['gw_name'] ?? 'Main Gateway';
        $gwType = $_POST['gw_type'] ?? 'openvox';
        $gwHost = $_POST['gw_host'] ?? '';
        $gwPort = $_POST['gw_port'] ?? 80;
        $gwUser = $_POST['gw_user'] ?? '';
        $gwPass = $_POST['gw_pass'] ?? '';
        $gwChannels = (int)($_POST['gw_channels'] ?? 8);
        
        if (empty($gwHost)) {
            $error = 'Gateway host is required';
        } else {
            try {
                require_once __DIR__ . '/includes/config.php';
                require_once __DIR__ . '/includes/database.php';
                
                $db = Database::getInstance();
                
                // Insert gateway
                $db->query(
                    "INSERT INTO gateways (name, type, host, port, username, password, channels, is_active, is_default, priority) 
                     VALUES (?, ?, ?, ?, ?, ?, ?, 1, 1, 10)",
                    [$gwName, $gwType, $gwHost, $gwPort, $gwUser, $gwPass, $gwChannels]
                );
                
                $gatewayId = $db->lastInsertId();
                
                // Generate ports
                for ($i = 1; $i <= $gwChannels; $i++) {
                    $db->query(
                        "INSERT INTO gateway_ports (gateway_id, port_number, port_name, is_active) VALUES (?, ?, ?, 1)",
                        [$gatewayId, $i, "Port $i"]
                    );
                }
                
                header('Location: install.php?step=complete');
                exit;
                
            } catch (Exception $e) {
                $error = 'Error: ' . $e->getMessage();
            }
        }
    }
}

// Check requirements
function checkRequirements() {
    $checks = [];
    
    $checks['php_version'] = [
        'name' => 'PHP Version >= 7.4',
        'ok' => version_compare(PHP_VERSION, '7.4.0', '>='),
        'value' => PHP_VERSION
    ];
    
    $checks['pdo'] = [
        'name' => 'PDO Extension',
        'ok' => extension_loaded('pdo'),
        'value' => extension_loaded('pdo') ? 'Loaded' : 'Not loaded'
    ];
    
    $checks['pdo_mysql'] = [
        'name' => 'PDO MySQL Driver',
        'ok' => extension_loaded('pdo_mysql'),
        'value' => extension_loaded('pdo_mysql') ? 'Loaded' : 'Not loaded'
    ];
    
    $checks['curl'] = [
        'name' => 'cURL Extension',
        'ok' => extension_loaded('curl'),
        'value' => extension_loaded('curl') ? 'Loaded' : 'Not loaded'
    ];
    
    $checks['json'] = [
        'name' => 'JSON Extension',
        'ok' => extension_loaded('json'),
        'value' => extension_loaded('json') ? 'Loaded' : 'Not loaded'
    ];
    
    $checks['config_writable'] = [
        'name' => 'Config file writable',
        'ok' => is_writable(__DIR__ . '/includes/config.php') || is_writable(__DIR__ . '/includes'),
        'value' => is_writable(__DIR__ . '/includes/config.php') ? 'Writable' : (is_writable(__DIR__ . '/includes') ? 'Will create' : 'Not writable')
    ];
    
    $checks['logs_dir'] = [
        'name' => 'Logs directory',
        'ok' => is_dir(__DIR__ . '/logs') && is_writable(__DIR__ . '/logs') || is_writable(__DIR__),
        'value' => is_dir(__DIR__ . '/logs') ? 'Exists' : 'Will be created'
    ];
    
    return $checks;
}

$checks = checkRequirements();
$allOk = !in_array(false, array_column($checks, 'ok'));

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMS Panel - Installation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body { background: #f5f6fa; }
        .install-container { max-width: 600px; margin: 50px auto; }
        .step-indicator { display: flex; justify-content: center; margin-bottom: 30px; }
        .step { width: 40px; height: 40px; border-radius: 50%; background: #dee2e6; 
                display: flex; align-items: center; justify-content: center; margin: 0 10px;
                font-weight: bold; color: #6c757d; position: relative; }
        .step.active { background: #3498db; color: white; }
        .step.completed { background: #27ae60; color: white; }
        .step-line { width: 40px; height: 2px; background: #dee2e6; align-self: center; }
        .step-line.completed { background: #27ae60; }
    </style>
</head>
<body>
    <div class="install-container">
        <div class="text-center mb-4">
            <h2><i class="bi bi-chat-dots text-primary"></i> SMS Panel</h2>
            <p class="text-muted">Installation Wizard v1.2</p>
        </div>
        
        <div class="step-indicator">
            <div class="step <?= $step === 'check' ? 'active' : ($step !== 'check' ? 'completed' : '') ?>">1</div>
            <div class="step-line <?= in_array($step, ['admin', 'gateway', 'complete']) ? 'completed' : '' ?>"></div>
            <div class="step <?= $step === 'database' ? 'active' : (in_array($step, ['admin', 'gateway', 'complete']) ? 'completed' : '') ?>">2</div>
            <div class="step-line <?= in_array($step, ['gateway', 'complete']) ? 'completed' : '' ?>"></div>
            <div class="step <?= $step === 'admin' ? 'active' : (in_array($step, ['gateway', 'complete']) ? 'completed' : '') ?>">3</div>
            <div class="step-line <?= $step === 'complete' ? 'completed' : '' ?>"></div>
            <div class="step <?= $step === 'gateway' ? 'active' : ($step === 'complete' ? 'completed' : '') ?>">4</div>
            <div class="step-line <?= $step === 'complete' ? 'completed' : '' ?>"></div>
            <div class="step <?= $step === 'complete' ? 'active' : '' ?>">5</div>
        </div>
        
        <?php if ($error): ?>
        <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>
        
        <div class="card">
            <?php if ($step === 'check'): ?>
            <div class="card-header">
                <i class="bi bi-check-circle me-2"></i> Step 1: System Requirements
            </div>
            <div class="card-body">
                <table class="table table-sm">
                    <?php foreach ($checks as $check): ?>
                    <tr>
                        <td><?= $check['name'] ?></td>
                        <td class="text-end">
                            <?php if ($check['ok']): ?>
                            <span class="badge bg-success"><?= $check['value'] ?></span>
                            <?php else: ?>
                            <span class="badge bg-danger"><?= $check['value'] ?></span>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                
                <?php if ($allOk): ?>
                <a href="?step=database" class="btn btn-primary w-100">
                    Continue <i class="bi bi-arrow-right"></i>
                </a>
                <?php else: ?>
                <div class="alert alert-warning mb-0">
                    Please fix the requirements above before continuing.
                </div>
                <?php endif; ?>
            </div>
            
            <?php elseif ($step === 'database'): ?>
            <div class="card-header">
                <i class="bi bi-database me-2"></i> Step 2: Database Configuration
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Database Host</label>
                        <input type="text" name="db_host" class="form-control" value="localhost" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database User</label>
                        <input type="text" name="db_user" class="form-control" value="root" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database Password</label>
                        <input type="password" name="db_pass" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database Name</label>
                        <input type="text" name="db_name" class="form-control" value="sms_panel" required>
                        <small class="text-muted">Will be created if doesn't exist</small>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">
                        Create Database <i class="bi bi-arrow-right"></i>
                    </button>
                </form>
            </div>
            
            <?php elseif ($step === 'admin'): ?>
            <div class="card-header">
                <i class="bi bi-person-circle me-2"></i> Step 3: Admin Account
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Username *</label>
                        <input type="text" name="admin_user" class="form-control" value="admin" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Password *</label>
                        <input type="password" name="admin_pass" class="form-control" required minlength="6">
                        <small class="text-muted">Minimum 6 characters</small>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Full Name</label>
                        <input type="text" name="admin_name" class="form-control" value="Administrator">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input type="email" name="admin_email" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary w-100">
                        Create Admin <i class="bi bi-arrow-right"></i>
                    </button>
                </form>
            </div>
            
            <?php elseif ($step === 'gateway'): ?>
            <div class="card-header">
                <i class="bi bi-hdd-network me-2"></i> Step 4: Gateway Configuration
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Gateway Name</label>
                        <input type="text" name="gw_name" class="form-control" value="Main Gateway" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Gateway Type</label>
                        <select name="gw_type" class="form-select">
                            <option value="openvox">OpenVox</option>
                            <option value="goip">GoIP</option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-8 mb-3">
                            <label class="form-label">Gateway Host (IP)</label>
                            <input type="text" name="gw_host" class="form-control" placeholder="192.168.1.100" required>
                        </div>
                        <div class="col-4 mb-3">
                            <label class="form-label">Port</label>
                            <input type="number" name="gw_port" class="form-control" value="80">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 mb-3">
                            <label class="form-label">Username</label>
                            <input type="text" name="gw_user" class="form-control" required>
                        </div>
                        <div class="col-6 mb-3">
                            <label class="form-label">Password</label>
                            <input type="password" name="gw_pass" class="form-control" required>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Number of Channels</label>
                        <select name="gw_channels" class="form-select">
                            <option value="1">1 channel</option>
                            <option value="4">4 channels</option>
                            <option value="8" selected>8 channels</option>
                            <option value="16">16 channels</option>
                            <option value="32">32 channels</option>
                            <option value="64">64 channels</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">
                        Save Gateway <i class="bi bi-arrow-right"></i>
                    </button>
                    <a href="?step=complete" class="btn btn-link w-100 mt-2">
                        Skip - I'll configure later
                    </a>
                </form>
            </div>
            
            <?php elseif ($step === 'complete'): ?>
            <div class="card-header bg-success text-white">
                <i class="bi bi-check-circle me-2"></i> Installation Complete!
            </div>
            <div class="card-body text-center">
                <i class="bi bi-check-circle text-success" style="font-size: 4rem;"></i>
                <h4 class="mt-3">SMS Panel is ready!</h4>
                <p class="text-muted">
                    Your SMS Panel has been successfully installed.
                </p>
                
                <div class="alert alert-warning text-start">
                    <strong><i class="bi bi-exclamation-triangle"></i> Security Reminder:</strong><br>
                    <ul class="mb-0 mt-2">
                        <li>Delete <code>install.php</code> after installation</li>
                        <li>Use HTTPS in production</li>
                        <li>Set proper file permissions</li>
                    </ul>
                </div>
                
                <a href="login.php" class="btn btn-success btn-lg">
                    <i class="bi bi-box-arrow-in-right me-2"></i> Login to SMS Panel
                </a>
            </div>
            <?php endif; ?>
        </div>
        
        <p class="text-center text-muted mt-3">
            <small>SMS Panel v1.2 &copy; <?= date('Y') ?></small>
        </p>
    </div>
</body>
</html>
